export const NOTES_FETCH_REQUEST = "NOTES_FETCH_REQUEST";
export const NOTES_FETCH_SUCCESS = "NOTES_FETCH_SUCCESS";
export const NOTES_FETCH_FAILED = "NOTES_FETCH_FAILED";

export const NOTES_POST_REQUEST = "NOTES_POST_REQUEST";
export const NOTES_POST_SUCCESS = "NOTES_POST_SUCCESS";
export const NOTES_POST_FAILED = "NOTES_POST_FAILED";

export const NOTES_UPDATE_REQUEST = "NOTES_UPDATE_REQUEST";
export const NOTES_UPDATE_SUCCESS = "NOTES_UPDATE_SUCCESS";
export const NOTES_UPDATE_FAILED = "NOTES_UPDATE_FAILED";

export const NOTES_DELETE_REQUEST = "NOTES_DELETE_REQUEST";
export const NOTES_DELETE_SUCCESS = "NOTES_DELETE_SUCCESS";
export const NOTES_DELETE_FAILED = "NOTES_DELETE_FAILED";